Import("env")

import os

PROJECT_DIR = env["PROJECT_DIR"]
ADMIN_INPUT = os.path.join(PROJECT_DIR, "html", "admin_ui.html")
EVIL_TWIN_INPUT = os.path.join(PROJECT_DIR, "html", "evil_twin.html")
OUTPUT_PATH = os.path.join(PROJECT_DIR, "src", "generated_htmls.h")
ADMIN_DELIM = "ADMINUI"
EVIL_TWIN_DELIM = "EVILTWINHTML"

missing = []
for path in (ADMIN_INPUT, EVIL_TWIN_INPUT):
    if not os.path.exists(path):
        missing.append(path)
if missing:
    raise FileNotFoundError("Missing HTML file(s): {}".format(", ".join(missing)))

with open(ADMIN_INPUT, "r", encoding="utf-8") as f:
    admin_html = f.read()

with open(EVIL_TWIN_INPUT, "r", encoding="utf-8") as f:
    evil_twin_html = f.read()

header = """#pragma once
#include <Arduino.h>
// Auto-generated by tools/embed_html.py. Do not edit by hand.
const char HEADER_TEMPLATE[] PROGMEM = R\"{admin_delim}({admin_body}){admin_delim}\";
const char EVIL_TWIN_HTML[] PROGMEM = R\"{evil_twin_delim}({evil_twin_body}){evil_twin_delim}\";
""".format(
    admin_delim=ADMIN_DELIM,
    admin_body=admin_html,
    evil_twin_delim=EVIL_TWIN_DELIM,
    evil_twin_body=evil_twin_html,
)

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(header)
