Import("env")

import os

PROJECT_DIR = env["PROJECT_DIR"]
ADMIN_INPUT = os.path.join(PROJECT_DIR, "html", "admin_ui.html")
CAPTIVE_INPUT = os.path.join(PROJECT_DIR, "html", "captive_portal.html")
OUTPUT_PATH = os.path.join(PROJECT_DIR, "src", "generated_htmls.h")
ADMIN_DELIM = "ADMINHTML"
CAPTIVE_DELIM = "CAPTIVEHTML"


def read_html_file(path):
    if not os.path.exists(path):
        raise FileNotFoundError("Missing HTML file: {}".format(path))
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    if "<html" not in content.lower():
        raise ValueError("Invalid HTML file (missing <html> tag): {}".format(path))
    return content


def generate_header_file(admin_body, captive_body):
    return """#pragma once
#include <Arduino.h>
// Auto-generated by tools/embed_html.py during build. Do not edit manually.
inline const char ADMIN_HEADER_HTML[] PROGMEM = R\"{admin_delim}({admin_body}){admin_delim}\";
inline const char CAPTIVE_PORTAL_HTML[] PROGMEM = R\"{captive_delim}({captive_body}){captive_delim}\";
inline const char FOOTER_HTML[] PROGMEM = "</div></body></html>";
""".format(
        admin_delim=ADMIN_DELIM,
        admin_body=admin_body,
        captive_delim=CAPTIVE_DELIM,
        captive_body=captive_body,
    )


def main():
    admin_html = read_html_file(ADMIN_INPUT)
    captive_html = read_html_file(CAPTIVE_INPUT)

    header_content = generate_header_file(admin_html, captive_html)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(header_content)

    print("Generated embedded HTML headers -> {}".format(OUTPUT_PATH))


main()
