[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = debug
lib_deps =
  bblanchon/ArduinoJson@^6.21.3

build_flags = -Wl,-z,muldefs
build_src_filter =
  +<main.cpp>
  +<ESP32_Attack_Platform.ino>
  +<deauth_utils.cpp>
  +<network_attacks.cpp>
  +<settings_manager.cpp>
